<a href="https://colab.research.google.com/github/Gaurav-29-eng/Anudip/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np;
print ("   1d Array");
a = np.array([[1,2.5,3,4,5]])
print (a)


   1d Array
[[1.  2.5 3.  4.  5. ]]


In [3]:
import numpy as np;
print ("      2d Array      ");
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print (b)

      2d Array      
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [4]:
import numpy as np;
print ("      3d Array      ");
c=np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print (c)

      3d Array      
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [5]:
type(a)
type(b)
type(c)

numpy.ndarray

In [6]:
print(a.size)
print(b.size)
print(c.size)

5
10
15


In [7]:
print(a.shape)
print(b.shape)
print(c.shape)

(1, 5)
(2, 5)
(1, 3, 5)


In [8]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

float64
int64
int64


In [9]:
a.transpose()

array([[1. ],
       [2.5],
       [3. ],
       [4. ],
       [5. ]])

In [10]:
b.transpose()

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [11]:
c.transpose()

array([[[ 1],
        [ 6],
        [11]],

       [[ 2],
        [ 7],
        [12]],

       [[ 3],
        [ 8],
        [13]],

       [[ 4],
        [ 9],
        [14]],

       [[ 5],
        [10],
        [15]]])

In [12]:
print(a.transpose())
print(b.transpose())
print(c.transpose())

[[1. ]
 [2.5]
 [3. ]
 [4. ]
 [5. ]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
[[[ 1]
  [ 6]
  [11]]

 [[ 2]
  [ 7]
  [12]]

 [[ 3]
  [ 8]
  [13]]

 [[ 4]
  [ 9]
  [14]]

 [[ 5]
  [10]
  [15]]]


In [13]:
np.empty((6,3),dtype=int)

array([[          999059824,                   0,           999183744],
       [    131945323687264, 3035475764848893962, 8028334170611412851],
       [3054967191141314153, 7300933268271008266, 8367810652205639014],
       [7310030967905740136, 7453010313415192691, 3631430073072902176],
       [7309464732520439876, 2338053640980886642, 8387219971351146349],
       [2308669005141666145, 7955973952031957024, 8026671738303820389]])

In [14]:
np.empty((6,3),dtype=bool)

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False]])

In [15]:
np.empty((6,3),dtype=str)

array([['', '', ''],
       ['', '', ''],
       ['', '', ''],
       ['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [16]:
np.ones((6,3), dtype = str)

array([['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [17]:
np.ones((6,3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
np.ones((6,3), dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [19]:
np.zeros((6,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
np.zeros((6,3), dtype = bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [21]:
np.zeros((6,3), dtype = str)

array([['', '', ''],
       ['', '', ''],
       ['', '', ''],
       ['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [27]:
a=np.arange(1,48,2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47]


In [28]:
a=a.reshape(8,3)
print(a)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]
 [19 21 23]
 [25 27 29]
 [31 33 35]
 [37 39 41]
 [43 45 47]]


In [33]:
b=np.arange(1,500,2)
print(b)

[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143
 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179
 181 183 185 187 189 191 193 195 197 199 201 203 205 207 209 211 213 215
 217 219 221 223 225 227 229 231 233 235 237 239 241 243 245 247 249 251
 253 255 257 259 261 263 265 267 269 271 273 275 277 279 281 283 285 287
 289 291 293 295 297 299 301 303 305 307 309 311 313 315 317 319 321 323
 325 327 329 331 333 335 337 339 341 343 345 347 349 351 353 355 357 359
 361 363 365 367 369 371 373 375 377 379 381 383 385 387 389 391 393 395
 397 399 401 403 405 407 409 411 413 415 417 419 421 423 425 427 429 431
 433 435 437 439 441 443 445 447 449 451 453 455 457 459 461 463 465 467
 469 471 473 475 477 479 481 483 485 487 489 491 49

In [35]:
b=b.reshape(25,10)
print(b)

[[  1   3   5   7   9  11  13  15  17  19]
 [ 21  23  25  27  29  31  33  35  37  39]
 [ 41  43  45  47  49  51  53  55  57  59]
 [ 61  63  65  67  69  71  73  75  77  79]
 [ 81  83  85  87  89  91  93  95  97  99]
 [101 103 105 107 109 111 113 115 117 119]
 [121 123 125 127 129 131 133 135 137 139]
 [141 143 145 147 149 151 153 155 157 159]
 [161 163 165 167 169 171 173 175 177 179]
 [181 183 185 187 189 191 193 195 197 199]
 [201 203 205 207 209 211 213 215 217 219]
 [221 223 225 227 229 231 233 235 237 239]
 [241 243 245 247 249 251 253 255 257 259]
 [261 263 265 267 269 271 273 275 277 279]
 [281 283 285 287 289 291 293 295 297 299]
 [301 303 305 307 309 311 313 315 317 319]
 [321 323 325 327 329 331 333 335 337 339]
 [341 343 345 347 349 351 353 355 357 359]
 [361 363 365 367 369 371 373 375 377 379]
 [381 383 385 387 389 391 393 395 397 399]
 [401 403 405 407 409 411 413 415 417 419]
 [421 423 425 427 429 431 433 435 437 439]
 [441 443 445 447 449 451 453 455 457 459]
 [461 463 4

In [29]:
a=a.flatten() #inverse of reshape #slow compared to ravel() #generates coy of original array #memory consuming
print(a)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47]


In [36]:
a=a.ravel() #fast compared to flatten() #geneates a view of the original array   #memory efficient
print(a)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47]


In [46]:
import numpy as np
a = np.arange(1,51)
a = a.reshape(10,5)
print(a)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [48]:
a[0]

array([1, 2, 3, 4, 5])

In [50]:
a[2]

array([11, 12, 13, 14, 15])

In [52]:
a[1,1] #prints the datatype of the value present on 1st row and 1st column

np.int64(7)

In [54]:
print(a[3,4]) #prints the value present on third row and 4th column of array a

20


In [55]:
a[2:5] #prints from row 2 to row 4 , 5th row is skipped

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [60]:
a[:5]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [58]:
a[0:100]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [62]:
a[2:5, 4] #goes from 2nd row to 4th row skipping 5th row and then going to 5th column and printing the value of 5th column from row 2 to row 4

array([15, 20, 25])

In [64]:
a[:, 2:5] #prints all the rows and column from 2 to 4 skipping 5th column

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25],
       [28, 29, 30],
       [33, 34, 35],
       [38, 39, 40],
       [43, 44, 45],
       [48, 49, 50]])

In [65]:
a[:, 2:5].dtype #prints the datatype present in all the rows and columns from 2 to 4

dtype('int64')